# Generated by Django 2.0.6 on 2018-10-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(max_length=50, null=True)),
                ('course_number', models.CharField(max_length=20, null=True)),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('course_list', models.CharField(max_length=20, null=True)),
                ('credit_hour', models.CharField(max_length=20, null=True)),
                ('test_type', models.CharField(max_length=20, null=True)),
                ('teacher', models.CharField(max_length=50, null=True)),
                ('course_week', models.CharField(max_length=20, null=True)),
                ('course_day', models.CharField(max_length=20, null=True)),
                ('course_time', models.CharField(max_length=20, null=True)),
                ('campus', models.CharField(max_length=20, null=True)),
                ('teaching_building', models.CharField(max_length=20, null=True)),
                ('classroom', models.CharField(max_length=20, null=True)),
                ('course_capacity', models.PositiveIntegerField(null=True)),
                ('course_limit', models.CharField(max_length=50, null=True)),
                ('course_start', models.PositiveIntegerField(null=True)),
                ('course_end', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schdule',
            name='teacher',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
