# Generated by Django 2.0.6 on 2018-11-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='course_number',
            new_name='course_name',
        ),
    ]
